apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: Sebastian.Neb@senacor.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-issuer-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: sandbox-sebastian-neb-7ca0
